private: # poa network
  tokenBridgeAddress:
  tokenBridgeAbi:
  dataBridgeAddress: 
  dataBridgeAbi: 
  sealerAddress: 
  sealerPassword:
  connectionMethod: 
  rpcUrl:
  ipcPath:
relay:
  private:
    contractAddress:
    contractAbi: 
ipfs:
  ip: 
  port:
main:
  payloadContractAddress: 
  payloadContractAbi: 
  adminAddress: 
  adminPassword:
  connectionMethod: 
  rpcUrl:
  ipcPath:
testToken:
  network:
  address:
  abiPath:
  account:
  accountPassword:
mainToken:
  network:
  address:
  abiPath:
  accuont:
  accountPassword:
